# API Project

https://www.opendata.nhs.scot/dataset/weekly-accident-and-emergency-activity-and-waiting-times/resource/a5f7ca94-c810-41b5-a7c9-25c18d43e5a4

### Import Libraries

In [8]:
import requests # For sending the API request
import json
from sqlalchemy import create_engine  # For connecting to a PostgreSQL database (or other databases)
import os
import pandas as pd

### Make the API request

In [9]:
# API URL
url = "https://www.opendata.nhs.scot/api/3/action/datastore_search"

# Parameters
params = {
    "resource_id": "a5f7ca94-c810-41b5-a7c9-25c18d43e5a4",
    "limit": 1300,
    "filters": json.dumps({"TreatmentLocation": "S308H"})
}

# Send the request
response = requests.get(url, params=params)

### Interpret the result

In [10]:
if response.status_code == 200:
    print(f"Request was a success! Status code: {response.status_code}")
else:
    print(f"Error: {response.status_code}")

Request was a success! Status code: 200

### Print the records

In [11]:
if response.status_code == 200:
    data = response.json()
    records = data.get("result", {}).get("records", [])  # Extract the records

### Add records to a data frame

In [12]:
import pandas as pd

# Convert records to a DataFrame
df = pd.DataFrame(records)

# Show the first few rows
df.tail()

,_id,WeekEndingDate,Country,HBT,TreatmentLocation,DepartmentType,AttendanceCategory,NumberOfAttendancesEpisode,NumberWithin4HoursEpisode,NumberOver4HoursEpisode,PercentageWithin4HoursEpisode,NumberOver8HoursEpisode,PercentageOver8HoursEpisode,NumberOver12HoursEpisode,PercentageOver12HoursEpisode
1264,40846,20260412,S92000003,S08000024,S308H,Type 1,Unplanned,1137,722,415,63.5,115,10.1,61,5.4
1265,40847,20260412,S92000003,S08000024,S308H,Type 1,All,1314,899,415,68.4,115,8.8,61,4.6
1266,40933,20260419,S92000003,S08000024,S308H,Type 1,New planned,207,207,0,100.0,0,0.0,0,0.0
1267,40934,20260419,S92000003,S08000024,S308H,Type 1,Unplanned,1196,673,523,56.3,153,12.8,81,6.8
1268,40935,20260419,S92000003,S08000024,S308H,Type 1,All,1403,880,523,62.7,153,10.9,81,5.8

# Transformation

In [13]:
df.columns = df.columns.str.lower()
df = df.drop(columns = ["country", "hbt"])
df.tail()

,_id,weekendingdate,treatmentlocation,departmenttype,attendancecategory,numberofattendancesepisode,numberwithin4hoursepisode,numberover4hoursepisode,percentagewithin4hoursepisode,numberover8hoursepisode,percentageover8hoursepisode,numberover12hoursepisode,percentageover12hoursepisode
1264,40846,20260412,S308H,Type 1,Unplanned,1137,722,415,63.5,115,10.1,61,5.4
1265,40847,20260412,S308H,Type 1,All,1314,899,415,68.4,115,8.8,61,4.6
1266,40933,20260419,S308H,Type 1,New planned,207,207,0,100.0,0,0.0,0,0.0
1267,40934,20260419,S308H,Type 1,Unplanned,1196,673,523,56.3,153,12.8,81,6.8
1268,40935,20260419,S308H,Type 1,All,1403,880,523,62.7,153,10.9,81,5.8

# Add data to the database

### Create connection to the database

In [14]:
# Create a connection to the database
db_user = "postgres"
db_password = os.environ.get("DB_PASSWORD")
db_host = "localhost"
db_port = "5432"
db_name = "A&E Attendances"

engine = create_engine(f"postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}")

with engine.connect() as conn:
    print("Connected to PostgreSQL successfully!")

Connected to PostgreSQL successfully!

### Load data into the database

In [15]:
existing_ids = pd.read_sql("SELECT _id FROM a_and_e_attendances", con=engine)['_id']
new_data = df[~df['_id'].isin(existing_ids)]

if not new_data.empty:
    new_data.to_sql("a_and_e_attendances", con=engine, if_exists="append", index=False)
    print(f"{len(new_data)} row(s) have been added to the database.")
else:
    print("Data already present within table.")

print("All data processed successfully!")

Data already present within table.
All data processed successfully!